image: "docker://ghcr.io/eessi/build-node:debian12"

host_injections: /opt/adm/eessi

fusemounts:
  - type: "container"
    fuse_cmd: "cvmfs2"
    fuse_arg: "cvmfs-config.cern.ch"
    ctr_mountpoint: "/cvmfs/cvmfs-config.cern.ch"
  - type: "container"
    fuse_cmd: "cvmfs2"
    fuse_arg: "software.eessi.io"
    ctr_mountpoint: "/cvmfs_ro/software.eessi.io"

writeable_repos: ["software.eessi.io"]
fuse_cmd_rw: unionfs
